version: "3.9"
services:
  postgres:
    container_name: keycloak_db
    image: postgres:latest
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "6433:5432"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
    ports:
      - 9999:8080
      - 9998:8443
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_URL_PORT: 5432
      KC_HTTPS_CERTIFICATE_FILE: /opt/certs/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/certs/localhost.key
    volumes:
      - ./cert:/opt/certs
      - ./keycloak/themes:/opt/bitnami/keycloak/themes/custom
      - ./keycloak/providers:/opt/bitnami/keycloak/providers
    depends_on:
      - postgres
volumes:
  keycloak_db_data:
    driver: local
