version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /home/administrator/opensource-app/volumes/minion:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ngocbao123
      MINIO_SERVER_URL: https://minio.phanmemvet.vn
      MINIO_BROWSER_REDIRECT_URL: https://consoleminio.phanmemvet.vn
    command: server --console-address ":9001" /data